# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from RoboCompAGM2ROS/structuralChangeProposalRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import RoboCompAGM2ROS.msg

class structuralChangeProposalRequest(genpy.Message):
  _md5sum = "57f80c331349cdccff7e018b20b4f255"
  _type = "RoboCompAGM2ROS/structuralChangeProposalRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """StructuralChangeStruct proposal

================================================================================
MSG: RoboCompAGM2ROS/StructuralChangeStruct
World model
Plan changes
string sender
string log

================================================================================
MSG: RoboCompAGM2ROS/World
Node[] nodes
Edge[] edges
int32 version
string lastEditor

================================================================================
MSG: RoboCompAGM2ROS/Node
StringPair[] attributes
int32 nodeIdentifier
string nodeType

================================================================================
MSG: RoboCompAGM2ROS/StringPair
string first
string second

================================================================================
MSG: RoboCompAGM2ROS/Edge
int32 a
int32 b
string edgeType
StringPair[] attributes

================================================================================
MSG: RoboCompAGM2ROS/Plan
Action[] actions
float32 cost

================================================================================
MSG: RoboCompAGM2ROS/Action
string name
StringPair[] symbols
"""
  __slots__ = ['proposal']
  _slot_types = ['RoboCompAGM2ROS/StructuralChangeStruct']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       proposal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(structuralChangeProposalRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.proposal is None:
        self.proposal = RoboCompAGM2ROS.msg.StructuralChangeStruct()
    else:
      self.proposal = RoboCompAGM2ROS.msg.StructuralChangeStruct()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.proposal.model.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.proposal.model.nodes:
        length = len(val1.attributes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.attributes:
          _x = val2.first
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2.second
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_i().pack(val1.nodeIdentifier))
        _x = val1.nodeType
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.proposal.model.edges)
      buff.write(_struct_I.pack(length))
      for val1 in self.proposal.model.edges:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.a, _x.b))
        _x = val1.edgeType
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.attributes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.attributes:
          _x = val2.first
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2.second
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_i().pack(self.proposal.model.version))
      _x = self.proposal.model.lastEditor
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.proposal.changes.actions)
      buff.write(_struct_I.pack(length))
      for val1 in self.proposal.changes.actions:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.symbols)
        buff.write(_struct_I.pack(length))
        for val2 in val1.symbols:
          _x = val2.first
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2.second
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_f().pack(self.proposal.changes.cost))
      _x = self.proposal.sender
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.proposal.log
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.proposal is None:
        self.proposal = RoboCompAGM2ROS.msg.StructuralChangeStruct()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.proposal.model.nodes = []
      for i in range(0, length):
        val1 = RoboCompAGM2ROS.msg.Node()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.attributes = []
        for i in range(0, length):
          val2 = RoboCompAGM2ROS.msg.StringPair()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.first = str[start:end].decode('utf-8')
          else:
            val2.first = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.second = str[start:end].decode('utf-8')
          else:
            val2.second = str[start:end]
          val1.attributes.append(val2)
        start = end
        end += 4
        (val1.nodeIdentifier,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.nodeType = str[start:end].decode('utf-8')
        else:
          val1.nodeType = str[start:end]
        self.proposal.model.nodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.proposal.model.edges = []
      for i in range(0, length):
        val1 = RoboCompAGM2ROS.msg.Edge()
        _x = val1
        start = end
        end += 8
        (_x.a, _x.b,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.edgeType = str[start:end].decode('utf-8')
        else:
          val1.edgeType = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.attributes = []
        for i in range(0, length):
          val2 = RoboCompAGM2ROS.msg.StringPair()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.first = str[start:end].decode('utf-8')
          else:
            val2.first = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.second = str[start:end].decode('utf-8')
          else:
            val2.second = str[start:end]
          val1.attributes.append(val2)
        self.proposal.model.edges.append(val1)
      start = end
      end += 4
      (self.proposal.model.version,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.proposal.model.lastEditor = str[start:end].decode('utf-8')
      else:
        self.proposal.model.lastEditor = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.proposal.changes.actions = []
      for i in range(0, length):
        val1 = RoboCompAGM2ROS.msg.Action()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.symbols = []
        for i in range(0, length):
          val2 = RoboCompAGM2ROS.msg.StringPair()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.first = str[start:end].decode('utf-8')
          else:
            val2.first = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.second = str[start:end].decode('utf-8')
          else:
            val2.second = str[start:end]
          val1.symbols.append(val2)
        self.proposal.changes.actions.append(val1)
      start = end
      end += 4
      (self.proposal.changes.cost,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.proposal.sender = str[start:end].decode('utf-8')
      else:
        self.proposal.sender = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.proposal.log = str[start:end].decode('utf-8')
      else:
        self.proposal.log = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.proposal.model.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.proposal.model.nodes:
        length = len(val1.attributes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.attributes:
          _x = val2.first
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2.second
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_i().pack(val1.nodeIdentifier))
        _x = val1.nodeType
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.proposal.model.edges)
      buff.write(_struct_I.pack(length))
      for val1 in self.proposal.model.edges:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.a, _x.b))
        _x = val1.edgeType
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.attributes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.attributes:
          _x = val2.first
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2.second
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_i().pack(self.proposal.model.version))
      _x = self.proposal.model.lastEditor
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.proposal.changes.actions)
      buff.write(_struct_I.pack(length))
      for val1 in self.proposal.changes.actions:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.symbols)
        buff.write(_struct_I.pack(length))
        for val2 in val1.symbols:
          _x = val2.first
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2.second
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_f().pack(self.proposal.changes.cost))
      _x = self.proposal.sender
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.proposal.log
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.proposal is None:
        self.proposal = RoboCompAGM2ROS.msg.StructuralChangeStruct()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.proposal.model.nodes = []
      for i in range(0, length):
        val1 = RoboCompAGM2ROS.msg.Node()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.attributes = []
        for i in range(0, length):
          val2 = RoboCompAGM2ROS.msg.StringPair()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.first = str[start:end].decode('utf-8')
          else:
            val2.first = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.second = str[start:end].decode('utf-8')
          else:
            val2.second = str[start:end]
          val1.attributes.append(val2)
        start = end
        end += 4
        (val1.nodeIdentifier,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.nodeType = str[start:end].decode('utf-8')
        else:
          val1.nodeType = str[start:end]
        self.proposal.model.nodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.proposal.model.edges = []
      for i in range(0, length):
        val1 = RoboCompAGM2ROS.msg.Edge()
        _x = val1
        start = end
        end += 8
        (_x.a, _x.b,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.edgeType = str[start:end].decode('utf-8')
        else:
          val1.edgeType = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.attributes = []
        for i in range(0, length):
          val2 = RoboCompAGM2ROS.msg.StringPair()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.first = str[start:end].decode('utf-8')
          else:
            val2.first = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.second = str[start:end].decode('utf-8')
          else:
            val2.second = str[start:end]
          val1.attributes.append(val2)
        self.proposal.model.edges.append(val1)
      start = end
      end += 4
      (self.proposal.model.version,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.proposal.model.lastEditor = str[start:end].decode('utf-8')
      else:
        self.proposal.model.lastEditor = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.proposal.changes.actions = []
      for i in range(0, length):
        val1 = RoboCompAGM2ROS.msg.Action()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.symbols = []
        for i in range(0, length):
          val2 = RoboCompAGM2ROS.msg.StringPair()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.first = str[start:end].decode('utf-8')
          else:
            val2.first = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.second = str[start:end].decode('utf-8')
          else:
            val2.second = str[start:end]
          val1.symbols.append(val2)
        self.proposal.changes.actions.append(val1)
      start = end
      end += 4
      (self.proposal.changes.cost,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.proposal.sender = str[start:end].decode('utf-8')
      else:
        self.proposal.sender = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.proposal.log = str[start:end].decode('utf-8')
      else:
        self.proposal.log = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from RoboCompAGM2ROS/structuralChangeProposalResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class structuralChangeProposalResponse(genpy.Message):
  _md5sum = "3bd113e2f12c9c571d32a0bd71d59b8d"
  _type = "RoboCompAGM2ROS/structuralChangeProposalResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 ret

"""
  __slots__ = ['ret']
  _slot_types = ['int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ret

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(structuralChangeProposalResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ret is None:
        self.ret = 0
    else:
      self.ret = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_i().pack(self.ret))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (self.ret,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_i().pack(self.ret))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (self.ret,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
class structuralChangeProposal(object):
  _type          = 'RoboCompAGM2ROS/structuralChangeProposal'
  _md5sum = 'ad99d108869abdd3f736a75426e14569'
  _request_class  = structuralChangeProposalRequest
  _response_class = structuralChangeProposalResponse
