# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from RoboCompAGM2ROS/EdgeSequence.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import RoboCompAGM2ROS.msg

class EdgeSequence(genpy.Message):
  _md5sum = "ce87345b17974240582f9f868ea89622"
  _type = "RoboCompAGM2ROS/EdgeSequence"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Edge[] EdgeSequence

================================================================================
MSG: RoboCompAGM2ROS/Edge
int32 a
int32 b
string edgeType
StringPair[] attributes

================================================================================
MSG: RoboCompAGM2ROS/StringPair
string first
string second
"""
  __slots__ = ['EdgeSequence']
  _slot_types = ['RoboCompAGM2ROS/Edge[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       EdgeSequence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EdgeSequence, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.EdgeSequence is None:
        self.EdgeSequence = []
    else:
      self.EdgeSequence = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.EdgeSequence)
      buff.write(_struct_I.pack(length))
      for val1 in self.EdgeSequence:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.a, _x.b))
        _x = val1.edgeType
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.attributes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.attributes:
          _x = val2.first
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2.second
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.EdgeSequence is None:
        self.EdgeSequence = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.EdgeSequence = []
      for i in range(0, length):
        val1 = RoboCompAGM2ROS.msg.Edge()
        _x = val1
        start = end
        end += 8
        (_x.a, _x.b,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.edgeType = str[start:end].decode('utf-8')
        else:
          val1.edgeType = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.attributes = []
        for i in range(0, length):
          val2 = RoboCompAGM2ROS.msg.StringPair()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.first = str[start:end].decode('utf-8')
          else:
            val2.first = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.second = str[start:end].decode('utf-8')
          else:
            val2.second = str[start:end]
          val1.attributes.append(val2)
        self.EdgeSequence.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.EdgeSequence)
      buff.write(_struct_I.pack(length))
      for val1 in self.EdgeSequence:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.a, _x.b))
        _x = val1.edgeType
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.attributes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.attributes:
          _x = val2.first
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2.second
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.EdgeSequence is None:
        self.EdgeSequence = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.EdgeSequence = []
      for i in range(0, length):
        val1 = RoboCompAGM2ROS.msg.Edge()
        _x = val1
        start = end
        end += 8
        (_x.a, _x.b,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.edgeType = str[start:end].decode('utf-8')
        else:
          val1.edgeType = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.attributes = []
        for i in range(0, length):
          val2 = RoboCompAGM2ROS.msg.StringPair()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.first = str[start:end].decode('utf-8')
          else:
            val2.first = str[start:end]
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.second = str[start:end].decode('utf-8')
          else:
            val2.second = str[start:end]
          val1.attributes.append(val2)
        self.EdgeSequence.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
